name: pin_otp_field
description: "A customizable Flutter widget for entering PIN or OTP codes, supporting various styles and input behaviors."
version: 0.0.4

homepage: 'https://github.com/suhail7cb/pin_opt_field'

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
